version: "3.9"

services:
  fastapiexample:
    build: "fastapiexample/"
    # ports: ["8080:80"] # To make port 8080 public
    networks: [vingnet]
    volumes:
      - ./fastapiexample/app:/code/app:ro
      - ./fastapiexample/app/data:/code/app/data
  nginx:
    image: "nginx"
    ports: ["8000:80"]
    networks: [vingnet]
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro

networks:
  vingnet:
