version: "3.9"

services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
      - ./mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE:vingnet
  mongo-express:
    image: mongo-express
    ports: ["8081:8081"]
    restart: always
    env_file:
      - /Users/torpand/.ssh/vingnet_secrets

  fastapiexample:
    build: "fastapiexample/"
    # ports: ["8080:80"] # To make port 8080 public
    volumes:
      - ./fastapiexample/app:/code/app:ro
      - ./fastapiexample/app/data:/code/app/data
  #fastapiexamplecron:
  #  build: "fastapiexample/fastapiexamplecron/"
  
  nginx:
    image: "nginx"
    ports: ["8000:80"]
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro

volumes:
  mongo:
